// <auto-generated />
using DemoAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoAPI.Data.Migrations
{
    [DbContext(typeof(DemoContext))]
    partial class DemoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.12");

            modelBuilder.Entity("DemoAPI.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int>("Old")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Student");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Marshall_Hahn",
                            Old = 63
                        },
                        new
                        {
                            Id = 2,
                            Name = "Gardner.Davis",
                            Old = 103
                        },
                        new
                        {
                            Id = 3,
                            Name = "Adam.Erdman49",
                            Old = 182
                        },
                        new
                        {
                            Id = 4,
                            Name = "Wava22",
                            Old = 19
                        },
                        new
                        {
                            Id = 5,
                            Name = "Broderick.Crona",
                            Old = 48
                        },
                        new
                        {
                            Id = 6,
                            Name = "Dennis.Hayes1",
                            Old = 36
                        },
                        new
                        {
                            Id = 7,
                            Name = "Madisen.Kautzer86",
                            Old = 135
                        },
                        new
                        {
                            Id = 8,
                            Name = "Tavares.Skiles",
                            Old = 200
                        },
                        new
                        {
                            Id = 9,
                            Name = "Elva11",
                            Old = 243
                        },
                        new
                        {
                            Id = 10,
                            Name = "Roscoe77",
                            Old = 177
                        },
                        new
                        {
                            Id = 11,
                            Name = "Judy.Krajcik45",
                            Old = 30
                        },
                        new
                        {
                            Id = 12,
                            Name = "Pasquale.Gottlieb",
                            Old = 138
                        },
                        new
                        {
                            Id = 13,
                            Name = "Leslie_Hamill",
                            Old = 230
                        },
                        new
                        {
                            Id = 14,
                            Name = "Coleman_Jacobson",
                            Old = 217
                        },
                        new
                        {
                            Id = 15,
                            Name = "Theron82",
                            Old = 95
                        },
                        new
                        {
                            Id = 16,
                            Name = "Asia_Herzog68",
                            Old = 106
                        },
                        new
                        {
                            Id = 17,
                            Name = "Hulda22",
                            Old = 83
                        },
                        new
                        {
                            Id = 18,
                            Name = "Norene_OConner94",
                            Old = 240
                        },
                        new
                        {
                            Id = 19,
                            Name = "Lonnie_Streich",
                            Old = 115
                        },
                        new
                        {
                            Id = 20,
                            Name = "Violet.Labadie14",
                            Old = 166
                        },
                        new
                        {
                            Id = 21,
                            Name = "Winnifred11",
                            Old = 216
                        },
                        new
                        {
                            Id = 22,
                            Name = "Torrance.Klocko",
                            Old = 71
                        },
                        new
                        {
                            Id = 23,
                            Name = "Elouise.Christiansen",
                            Old = 184
                        },
                        new
                        {
                            Id = 24,
                            Name = "Orlo.Schuppe94",
                            Old = 212
                        },
                        new
                        {
                            Id = 25,
                            Name = "Austyn.Kozey22",
                            Old = 209
                        },
                        new
                        {
                            Id = 26,
                            Name = "Antoinette71",
                            Old = 81
                        },
                        new
                        {
                            Id = 27,
                            Name = "Liza48",
                            Old = 25
                        },
                        new
                        {
                            Id = 28,
                            Name = "Johnson_Wisozk45",
                            Old = 110
                        },
                        new
                        {
                            Id = 29,
                            Name = "Destiny_Johnson",
                            Old = 89
                        },
                        new
                        {
                            Id = 30,
                            Name = "Garnet89",
                            Old = 54
                        },
                        new
                        {
                            Id = 31,
                            Name = "Amber_Donnelly39",
                            Old = 30
                        },
                        new
                        {
                            Id = 32,
                            Name = "Jaqueline_McCullough36",
                            Old = 8
                        },
                        new
                        {
                            Id = 33,
                            Name = "Ciara_Beer",
                            Old = 176
                        },
                        new
                        {
                            Id = 34,
                            Name = "Christina68",
                            Old = 172
                        },
                        new
                        {
                            Id = 35,
                            Name = "Kenneth_Schuppe49",
                            Old = 250
                        },
                        new
                        {
                            Id = 36,
                            Name = "Cody.Prosacco",
                            Old = 172
                        },
                        new
                        {
                            Id = 37,
                            Name = "Leanne.Gislason",
                            Old = 163
                        },
                        new
                        {
                            Id = 38,
                            Name = "Beulah8",
                            Old = 193
                        },
                        new
                        {
                            Id = 39,
                            Name = "Dominique.Boyle",
                            Old = 248
                        },
                        new
                        {
                            Id = 40,
                            Name = "Geovanny_Renner14",
                            Old = 174
                        },
                        new
                        {
                            Id = 41,
                            Name = "Paula93",
                            Old = 188
                        },
                        new
                        {
                            Id = 42,
                            Name = "Carolina.Williamson",
                            Old = 224
                        },
                        new
                        {
                            Id = 43,
                            Name = "Ricardo30",
                            Old = 222
                        },
                        new
                        {
                            Id = 44,
                            Name = "Jordy.Kub25",
                            Old = 110
                        },
                        new
                        {
                            Id = 45,
                            Name = "Brycen48",
                            Old = 112
                        },
                        new
                        {
                            Id = 46,
                            Name = "Tod36",
                            Old = 65
                        },
                        new
                        {
                            Id = 47,
                            Name = "Uriah50",
                            Old = 178
                        },
                        new
                        {
                            Id = 48,
                            Name = "Twila_Powlowski",
                            Old = 136
                        },
                        new
                        {
                            Id = 49,
                            Name = "Jamel97",
                            Old = 87
                        },
                        new
                        {
                            Id = 50,
                            Name = "Aubrey15",
                            Old = 226
                        },
                        new
                        {
                            Id = 51,
                            Name = "Marcos_Pouros79",
                            Old = 136
                        },
                        new
                        {
                            Id = 52,
                            Name = "Krystal_Bashirian48",
                            Old = 75
                        },
                        new
                        {
                            Id = 53,
                            Name = "Kareem.Heaney34",
                            Old = 18
                        },
                        new
                        {
                            Id = 54,
                            Name = "Elton.McClure9",
                            Old = 215
                        },
                        new
                        {
                            Id = 55,
                            Name = "Hayley.Herman91",
                            Old = 215
                        },
                        new
                        {
                            Id = 56,
                            Name = "Frankie97",
                            Old = 132
                        },
                        new
                        {
                            Id = 57,
                            Name = "Carolanne.Corwin15",
                            Old = 213
                        },
                        new
                        {
                            Id = 58,
                            Name = "Xzavier15",
                            Old = 231
                        },
                        new
                        {
                            Id = 59,
                            Name = "Judge58",
                            Old = 32
                        },
                        new
                        {
                            Id = 60,
                            Name = "Trycia_Lindgren",
                            Old = 220
                        },
                        new
                        {
                            Id = 61,
                            Name = "Felipe.Abernathy",
                            Old = 174
                        },
                        new
                        {
                            Id = 62,
                            Name = "Evan3",
                            Old = 167
                        },
                        new
                        {
                            Id = 63,
                            Name = "Leila6",
                            Old = 80
                        },
                        new
                        {
                            Id = 64,
                            Name = "Delia.Fadel",
                            Old = 190
                        },
                        new
                        {
                            Id = 65,
                            Name = "Merlin.Fritsch17",
                            Old = 40
                        },
                        new
                        {
                            Id = 66,
                            Name = "Earlene_Hintz96",
                            Old = 4
                        },
                        new
                        {
                            Id = 67,
                            Name = "Oleta.Moen",
                            Old = 33
                        },
                        new
                        {
                            Id = 68,
                            Name = "Curtis.Kuhn5",
                            Old = 123
                        },
                        new
                        {
                            Id = 69,
                            Name = "Jammie.Osinski",
                            Old = 30
                        },
                        new
                        {
                            Id = 70,
                            Name = "Cedrick_Block",
                            Old = 222
                        },
                        new
                        {
                            Id = 71,
                            Name = "Coleman23",
                            Old = 86
                        },
                        new
                        {
                            Id = 72,
                            Name = "Brody77",
                            Old = 123
                        },
                        new
                        {
                            Id = 73,
                            Name = "Jayne48",
                            Old = 235
                        },
                        new
                        {
                            Id = 74,
                            Name = "Logan_Koss",
                            Old = 160
                        },
                        new
                        {
                            Id = 75,
                            Name = "Katherine.Hickle",
                            Old = 190
                        },
                        new
                        {
                            Id = 76,
                            Name = "Garrick_Schowalter69",
                            Old = 195
                        },
                        new
                        {
                            Id = 77,
                            Name = "Jolie.Keeling",
                            Old = 29
                        },
                        new
                        {
                            Id = 78,
                            Name = "Jaycee_Cremin31",
                            Old = 230
                        },
                        new
                        {
                            Id = 79,
                            Name = "Muriel.Blick45",
                            Old = 239
                        },
                        new
                        {
                            Id = 80,
                            Name = "Monique.Larkin88",
                            Old = 117
                        },
                        new
                        {
                            Id = 81,
                            Name = "Holden85",
                            Old = 137
                        },
                        new
                        {
                            Id = 82,
                            Name = "Kaelyn_Fadel75",
                            Old = 113
                        },
                        new
                        {
                            Id = 83,
                            Name = "Malika_Stroman86",
                            Old = 106
                        },
                        new
                        {
                            Id = 84,
                            Name = "Jamey_Lockman46",
                            Old = 111
                        },
                        new
                        {
                            Id = 85,
                            Name = "Asia_Douglas",
                            Old = 183
                        },
                        new
                        {
                            Id = 86,
                            Name = "Darren61",
                            Old = 170
                        },
                        new
                        {
                            Id = 87,
                            Name = "Shanny37",
                            Old = 184
                        },
                        new
                        {
                            Id = 88,
                            Name = "Bennie.Block",
                            Old = 130
                        },
                        new
                        {
                            Id = 89,
                            Name = "Jerad.Corwin12",
                            Old = 16
                        },
                        new
                        {
                            Id = 90,
                            Name = "Claud_Heller",
                            Old = 49
                        },
                        new
                        {
                            Id = 91,
                            Name = "Bailee.Labadie",
                            Old = 255
                        },
                        new
                        {
                            Id = 92,
                            Name = "Breanna48",
                            Old = 183
                        },
                        new
                        {
                            Id = 93,
                            Name = "Meaghan64",
                            Old = 31
                        },
                        new
                        {
                            Id = 94,
                            Name = "Octavia.Brown22",
                            Old = 10
                        },
                        new
                        {
                            Id = 95,
                            Name = "Jane.Legros74",
                            Old = 106
                        },
                        new
                        {
                            Id = 96,
                            Name = "Juliet.Koepp",
                            Old = 169
                        },
                        new
                        {
                            Id = 97,
                            Name = "Jerald71",
                            Old = 65
                        },
                        new
                        {
                            Id = 98,
                            Name = "Reina.Rohan",
                            Old = 61
                        },
                        new
                        {
                            Id = 99,
                            Name = "Annalise_Fisher",
                            Old = 233
                        },
                        new
                        {
                            Id = 100,
                            Name = "Abbie_Willms",
                            Old = 186
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
